services:
  server:
    build:
      context:   "" 
      dockerfile: "serveur.dockerfile"
    container_name: serveur_tache
    ports:
      - "5000:5000"            
    restart: unless-stopped

  client:
    build:
      context:  ""     
      dockerfile: "client.dockerfile"
    container_name: client_tache
    network_mode: "host"       
    restart: unless-stopped
